# Generated by Django 5.0.7 on 2024-09-16 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('date_registered', models.DateField(auto_now_add=True)),
                ('file', models.FileField(upload_to='announcements/')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('program_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('program_duration', models.IntegerField()),
                ('date_registered', models.DateField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.department')),
            ],
        ),
        migrations.CreateModel(
            name='Herroes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('heading', models.CharField(max_length=200)),
                ('title', models.CharField(choices=[('Best_Student', 'Best Student'), ('Best_Staff', 'Best Staff'), ('Best_Footbal_Winner', 'Best Footbal Winner'), ('Best_Leader', 'Best Leader')], max_length=100)),
                ('image', models.ImageField(upload_to='herroes/')),
                ('date_registered', models.DateField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.department')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.programs')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.programs')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('regno', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('passport_size', models.ImageField(upload_to='passports/')),
                ('application_form', models.FileField(upload_to='applications/')),
                ('date_registered', models.DateField(auto_now_add=True)),
                ('resident', models.CharField(choices=[('Tanzania', 'Default'), ('Dodoma', 'Dodoma'), ('Tanga', 'Tanga'), ('Arusha', 'Arusha'), ('Tabora', 'Tabora')], max_length=100)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.programs')),
            ],
        ),
    ]
