# Generated by Django 5.1.3 on 2024-11-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=200)),
                ('faculty', models.CharField(choices=[('Faculty of Science', 'Faculty of Science'), ('Faculty of Humanities and Business Studies', 'Faculty of Humanities and Business Studies'), ('education', 'education')], max_length=200)),
                ('Course', models.CharField(choices=[('Doctor of Philosophy in Education', 'Doctor of Philosophy in Education'), ('Master of Education', 'Master of Education'), ('Master of Business Administration ', 'Master of Business Administration '), ('Postgraduate Diploma in Education', 'Postgraduate Diploma in Education'), ('Bachelor of Education in Science', 'Bachelor of Education in Science'), ('Bachelor of Education in Arts', 'Bachelor of Education in Arts'), ('Bachelor of Geography and Environmental Studies', 'Bachelor of Geography and Environmental Studies'), ('Bachelor of Science in Mathematics and Statistics', 'Bachelor of Science in Mathematics and Statistics'), ('Bachelor of Sociology and Social Work', 'Bachelor of Sociology and Social Work'), ('Bachelor of Business Administration', 'Bachelor of Business Administration'), ('Bachelor of Philosophy with Ethics', 'Bachelor of Philosophy with Ethics'), ('Bachelor of Procurement and Supply Chain Management', 'Bachelor of Procurement and Supply Chain Management'), ('Bachelor of Science in Applied Biolog', 'Bachelor of Science in Applied Biolog'), ('Bachelor of Science in Chemistry', 'Bachelor of Science in Chemistry'), ('Bachelor of Science in Computer Science', 'Bachelor of Science in Computer Science')], max_length=200)),
                ('department', models.CharField(choices=[('Department of Natural Sciences and Information Technology', 'Department of Natural Sciences and Information Technology'), ('Department of Agriculture, Earth and Environmental Sciences', 'Department of Agriculture, Earth and Environmental Sciences'), ('Department of Social Sciences and Humanities', 'Department of Social Sciences and Humanities'), ('Directorate of Non-Degree Programmes', 'Directorate of Non-Degree Programmes')], max_length=200)),
                ('academic_year', models.CharField(choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026')], max_length=200)),
                ('project_title', models.CharField(max_length=200)),
                ('date_registered', models.DateField(auto_now_add=True)),
                ('research_document', models.FileField(upload_to='research/')),
                ('image', models.ImageField(upload_to='application/')),
                ('status', models.CharField(choices=[('Pending...', 'Pending...'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=200)),
            ],
        ),
    ]
