# Generated by Django 5.1.3 on 2024-11-17 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='full_name',
            new_name='Student_name',
        ),
        migrations.RenameField(
            model_name='herroes',
            old_name='full_name',
            new_name='Student_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='full_name',
            new_name='Student_name',
        ),
    ]
